# Generated by Django 3.2.23 on 2024-01-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='privacy_setting',
            field=models.BooleanField(default=False),
        ),
    ]
