# Generated by Django 3.2.23 on 2024-01-24 18:25

from django.conf import settings
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('api', '0002_alter_customuser_privacy_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='subscribed_members',
            field=models.ManyToManyField(blank=True, related_name='subscribed_forums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
